### ISSUE TITLE
Integer parsing doesn't fail on i-0e

### ISSUE THREAD

**Issue by PuercoPop** [ivoscc/racket-torrent#2]
`(parse-integer (open-input-string "i-0e")) => 0`

which is invalid as per [BEP-003](http://www.bittorrent.org/beps/bep_0003.html)
```
All encodings with a leading zero, such as i03e, are invalid, other than i0e, which of course corresponds to 0.
```

**Comment by ivoscc** [comment]
Thanks! Will work on a patch for that.

**Comment by PuercoPop** [comment]
Nice!
